### ISSUE TITLE
Crear clases

### ISSUE THREAD

**Issue by EduardoSo7o** [GerardoPrz/greenFoot.pacman#2]
Crear las clases:
- Record
- Juego
- Ayuda

**Comment by iuresti** [comment]
El título de los issues debe platicar de manera general qué se espera al resolver el ticket ... en la descripción se desglosa lo que llamamos el acceptance criteria (que viene siendo el detalle de lo que se espera del ticket).

"Crear clases" no aporta valor al juego como tal ... los issues deben ser más del estilo "Añadir funcionalidad de guardar record" o "Visualizar records" y en la descripción detallas en qué momento y con qué botón/comando/acción se guardarán los records.. o bien la ruta para visualizar los records
